--- 
title: 'HarvardX 125.9x Project: Higgs dataset classification'
author: "Yin-Chi Chan"
date: "`r Sys.Date()`"
documentclass: article
mainfont: Times New Roman
monofont: Fira Code
geometry: margin=2.5cm
bibliography: book.bib
biblio-style: acm
description: |
  See also: _output.yml, _bookdown.yml
link-citations: yes
site: bookdown::bookdown_site
---

# Preface {-}

This template generates output in both [HTML](index.html) and [PDF](higgs.pdf) form.
Code chunks are typeset in 
[Fira Code](https://github.com/tonsky/FiraCode), with code ligatures enabled.

## R setup

```{r Setup, include=FALSE, purl=FALSE}

knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  dpi = 144
)

# Shrink code font size relative to main text in PDF output
# https://stackoverflow.com/questions/25646333/#46526740
def.chunk.hook  <- knitr::knit_hooks$get("chunk")
if (knitr::is_latex_output()) {
  knitr::knit_hooks$set(chunk = function(x, options) {
    x <- def.chunk.hook(x, options)
    paste0("\n \\", "small","\n\n", x, "\n\n \\normalsize")
  })
}
```

```{r Load-libraries}

# R 4.1 key features: new pipe operator, \(x) as shortcut for function(x)
# R 4.0 key features: stringsAsFactors = FALSE by default, raw character strings r"()"
if (packageVersion('base') < '4.1.0') {
  stop('This code requires R >= 4.1.0!')
}

if(!require("pacman")) install.packages("pacman")
if(!require("keras")) {
  install.packages("keras")
  keras::install_keras()
}

library(pacman)
p_load(data.table, dtplyr, tidyverse, R.utils, Rfast, knitr,
       keras, caret, pROC, knitr, conflicted)
conflict_prefer('summarize', 'dplyr')
conflict_prefer('summarise', 'dplyr')
conflict_prefer('filter', 'dplyr')
conflict_prefer('between', 'dplyr')
conflict_prefer('auc', 'pROC')

# Somehow, this seems to prevent memory leaks
tensorflow::tf$compat$v1$disable_eager_execution()
```
