--- 
title: 'Gitbook template'
author: "Firstname Lastname"
date: "`r Sys.Date()`"
documentclass: article
mainfont: Times New Roman
mathfont: Cambria Math
monofont: Cascadia Code
geometry: margin=2.5cm
bibliography: book.bib
biblio-style: acm
description: |
  See also: _output.yml, _bookdown.yml
link-citations: yes
site: bookdown::bookdown_site
---

# Preface {-}

This template generates output in both [HTML](index.html) and [PDF](merged.pdf) form.
Code in the PDF output is typeset in 
[Cascadia Code](https://github.com/microsoft/cascadia-code), with code ligatures enabled.
A similar font, [Fira Code](https://github.com/tonsky/FiraCode), is used in the HTML version.

## R setup

```{r Setup, include=FALSE, purl=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  dpi = 144
)

# Shrink code font size relative to main text in PDF output
# https://stackoverflow.com/questions/25646333/#46526740
def.chunk.hook  <- knitr::knit_hooks$get("chunk")
if (knitr::is_latex_output()) {
  knitr::knit_hooks$set(chunk = function(x, options) {
    x <- def.chunk.hook(x, options)
    paste0("\n \\", "small","\n\n", x, "\n\n \\normalsize")
  })
}
```

```{r Load-libraries}

# R 4.1 key features: new pipe operator, \(x) as shortcut for function(x)
# R 4.0 key features: stringsAsFactors = FALSE by default, raw character strings r"()"
if (packageVersion('base') < '4.1.0') {
  stop('This code requires R >= 4.1.0!')
}

if(!require("pacman")) install.packages("pacman")
library(pacman)
p_load(tidyverse)
```

Plot example: Anscombe's quartet @Anscombe1973

```{r Plot-example, fig.height=7, fig.width=7}
anscombe %>% 
  gather(variable.x, value, -y1, -y2, -y3, -y4) |>
  select(variable.x = value) |>
  bind_cols(gather(anscombe, variable, value, -x1, -x2, -x3, -x4)) |>
  select(x = variable.x, variable, y = value) |>
  ggplot(aes(x,y)) + facet_wrap(~variable) +
  geom_point() + stat_smooth(method="lm",fullrange=T,se=F) +
  theme(aspect.ratio=1.)
```


<!--chapter:end:index.Rmd-->

# References {-}

<div id="refs"></div>

<!--chapter:end:91-references.Rmd-->

